version: "3.4"

services:
  php:
    build:
      context: .
      target: symfony_php
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      DATABASE_URL: sqlite:///%kernel.project_dir%/var/data.db

  nginx:
    build:
      context: .
      target: symfony_nginx
    depends_on:
      - php
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-8080}
        protocol: tcp


volumes:
  php_socket:

